printWidth: 100
quoteProps: "preserve"
importOrder:
  [
    "^react",
    "^next",
    "^@",
    "^(?<!(components|utils|data))/.*$",
    "^[A-Za-z0-9_-]*$",
    "^(components|utils|data)/.*$",
    "^[./]",
  ]
importOrderSeparation: true
importOrderSortSpecifiers: true
