services:
  postgres:
    image: postgres:16
    restart: on-failure
    # hostname: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db_dev
