# deleteCosmosContainers
POST http://localhost:7071/api/deleteCosmosContainers
content-type: application/json

{
    "databaseId": "Amami",
    "containers": ["Data_jiang-local-1", "Data_jiang-local-2"]
}